export const jwtConstants = {
  secret: `-----BEGIN PRIVATE KEY-----
  MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAz9eXNIlwtZBJFINX
  YzHNO6k+LzZEtKYPNsVohlUBFRmNjCxVcGAdLLhFYxBQH8jW2fiRp/VxKwVxF+ZI
  Zn3JMwIDAQABAkAgvcGgERakQ3p/tMELa0j9YQfewBnKq24yHp78ql9lRzyMPCnH
  DVF30Sp/YCG+2OyQPsfBW/h0b/rwojOfX5GBAiEA51xGuVjKKcM7dr7wxyPJjGK5
  MHpEbLy5dfUDr3IioeMCIQDl+h7KVRqM00EKI7X5FxusPAyyAwxSrcPpqgw/2Jqc
  cQIgf/+7WRvYbRaINYAZ8fLItRSBZGKgrJAVAz+U1GIO6wUCICJ9ucJ0sw+t21JO
  +srJ6W+SbgEArgd0Yi6YP1AQB1gxAiEAtZMvpR9lgu7q3C/U521HUjbmeLgICsN6
  DZ5ddjF97uY=
  -----END PRIVATE KEY-----`,
};

`-----BEGIN PUBLIC KEY-----
MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAM/XlzSJcLWQSRSDV2MxzTupPi82RLSm
DzbFaIZVARUZjYwsVXBgHSy4RWMQUB/I1tn4kaf1cSsFcRfmSGZ9yTMCAwEAAQ==
-----END PUBLIC KEY-----`;
